# Generated by Django 3.2.4 on 2022-02-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='ins',
            new_name='bat_ins',
        ),
        migrations.AddField(
            model_name='players',
            name='bowl_ins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='bowl_status',
            field=models.CharField(choices=[('Not Bowling', 'Nbw'), ('Bowling', 'Bw'), ('Recent', 'Bw'), ('Bowled', 'Bwl')], default='Not Bowling', max_length=100),
        ),
    ]
