# Generated by Django 3.2.4 on 2022-02-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='bolw_average',
            new_name='bowl_average',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='bolw_balls',
            new_name='bowl_balls',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='bolw_best_bowling',
            new_name='bowl_best_bowling',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='bolw_economy',
            new_name='bowl_economy',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='bolw_five_wkt',
            new_name='bowl_five_wkt',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='bolw_runs',
            new_name='bowl_runs',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='bolw_three_wkt',
            new_name='bowl_three_wkt',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='bolw_wicket',
            new_name='bowl_wicket',
        ),
    ]
