# Generated by Django 3.2.4 on 2022-02-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_auto_20220226_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='is_bat_inn_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerscore',
            name='is_bat_inn_two',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerscore',
            name='is_bowl_inn_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerscore',
            name='is_bowl_inn_two',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='bat_status',
            field=models.CharField(choices=[('Not Batting', 'Nbt'), ('Batting', 'Bt'), ('Out', 'ot'), ('Continue Bat', 'cbl')], default='Not Batting', max_length=100),
        ),
    ]
