# Generated by Django 3.2.4 on 2022-02-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_auto_20220220_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinfo',
            name='first_ins_crr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='second_ins_crr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='second_ins_rrr',
            field=models.FloatField(default=0.0),
        ),
    ]
