# Generated by Django 3.2.4 on 2022-02-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_auto_20220220_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinfo',
            name='first_ins_extra_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='second_ins_extra_runs',
            field=models.IntegerField(default=0),
        ),
    ]
