# Generated by Django 3.2.4 on 2022-02-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0004_auto_20220220_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchinfo',
            name='second_ins_rrr',
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='bowl_status',
            field=models.CharField(choices=[('Not Bowling', 'Nbw'), ('Bowling', 'Bw'), ('Recent', 'Bw')], default='Not Bowling', max_length=100),
        ),
    ]
